### ISSUE TITLE
stm32pinout.py: some info

### ISSUE THREAD

**Issue by fpistm** [matthijskooijman/scripts#2]
Hi @matthijskooijman 

I've ended up here reading one of your blog post.
Maybe you already know that but just in case, a part of the STM32 mcu db (included in STM32CubeMX) is now available on GitHub:
https://github.com/STMicroelectronics/STM32_open_pin_data

About this:
https://github.com/matthijskooijman/scripts/blob/30bf5122b44d4df48b350ea230e2c7456b7c59a6/embedded/stm32pinout.py#L59-L68

We also use thoses db to generate some of our generic files and so several of the TODO are done in this script:
https://github.com/stm32duino/Arduino_Core_STM32/blob/main/CI/update/stm32variant.py

Which allows to generate the generic variant including the PeripheralPins.c. 

Hope this was useful.
Feel free to close this issue as it is mainly to provide some information. 😉

**Comment by matthijskooijman** [comment]
@fpistm Cool, thanks for the pointers. I really like that ST is using github and is opening up development more, really cool.

**Comment by matthijskooijman** [comment]
I've updated my blogpost with some of your info.
